### ISSUE TITLE
Log to file in methods of Field class.

### ISSUE THREAD

**Issue by wraxen** [SqueezyWeb/Database#6]
Methods in which a log is (maybe) needed:
- `Freyja\Database\Schema\Field::getLength()` when the default length is chosen instead of the one specified.
- `Freyja\Database\Schema\Schema::create()` when the table already exists, or when the table has been correctly created.
- `Freyja\Database\Schema\Schema::remove()` when the table doesn't exists, or when the table has been correctly removed.
- `Freyja\Database\Schema\Schema::alter()` when the table doesn't exists, or when the table has been correctly alterated.

**Comment by deshack** [comment]
Ok, I think none of these cases really need logging, so just drop this shit.
